
INSERT INTO `ONPE_DEV`.`class_community`(community_number,
                                     community_class_code,
                                     community_id,
                                     community_name,
                                     community_title,
                                     community_text,
                                     community_date,
                                     community_file1,
                                     community_file2,
                                     community_count,
                                     community_auth)
     VALUES (103,
             '서종중학교_1011510',
             'skqkrclgh2',
             '박치호',
             '야호',
             '야호',
             20210330201142,
             NULL,
             NULL,
             0,
             NULL);
INSERT INTO `ONPE_DEV`.`class_community`(community_number,
                                     community_class_code,
                                     community_id,
                                     community_name,
                                     community_title,
                                     community_text,
                                     community_date,
                                     community_file1,
                                     community_file2,
                                     community_count,
                                     community_auth)
     VALUES (104,
             '형남중학교_1011789',
             'com1023',
             '엄현주',
             '안녕',
             '안녕 친구들',
             20210401120315,
             NULL,
             NULL,
             2,
             NULL);
INSERT INTO `ONPE_DEV`.`class_community`(community_number,
                                     community_class_code,
                                     community_id,
                                     community_name,
                                     community_title,
                                     community_text,
                                     community_date,
                                     community_file1,
                                     community_file2,
                                     community_count,
                                     community_auth)
     VALUES (109,
             '고려유치원_2011664',
             'jsh9870',
             '조성훈',
             '1658',
             '기록 기록 기록ㄴㄱㄴㄱㄴㄱㄴㄱㄴ',
             20210609165909,
             NULL,
             NULL,
             6,
             NULL);
INSERT INTO `ONPE_DEV`.`class_community`(community_number,
                                     community_class_code,
                                     community_id,
                                     community_name,
                                     community_title,
                                     community_text,
                                     community_date,
                                     community_file1,
                                     community_file2,
                                     community_count,
                                     community_auth)
     VALUES (111,
             '고려유치원_2011664',
             'jsh9870',
             '조성훈',
             '1702',
             '학생이 남긴 커뮤니티 글',
             20210609170207,
             NULL,
             NULL,
             0,
             NULL);
INSERT INTO `ONPE_DEV`.`class_community`(community_number,
                                     community_class_code,
                                     community_id,
                                     community_name,
                                     community_title,
                                     community_text,
                                     community_date,
                                     community_file1,
                                     community_file2,
                                     community_count,
                                     community_auth)
     VALUES (112,
             '고려유치원_2011664',
             'jsh9870',
             '조성훈',
             '첨부파일',
             '첨부파일이 있는 글',
             20210609172647,
             '/resources/community_file/20210609172645_jsh9870_0.jpg',
             NULL,
             0,
             NULL);
INSERT INTO `ONPE_DEV`.`class_community`(community_number,
                                     community_class_code,
                                     community_id,
                                     community_name,
                                     community_title,
                                     community_text,
                                     community_date,
                                     community_file1,
                                     community_file2,
                                     community_count,
                                     community_auth)
     VALUES (113,
             '고려유치원_2011664',
             'jsh9870',
             '조성훈',
             '아아아아',
             '아아아아',
             20210609175553,
             NULL,
             NULL,
             1,
             NULL);
INSERT INTO `ONPE_DEV`.`class_community`(community_number,
                                     community_class_code,
                                     community_id,
                                     community_name,
                                     community_title,
                                     community_text,
                                     community_date,
                                     community_file1,
                                     community_file2,
                                     community_count,
                                     community_auth)
     VALUES (114,
             '고려유치원_1011534',
             'jsh9870',
             '조성훈',
             '게시판 글쓰기???????????',
             '& lt;p& gt;ㅇㅇ10글자를 사용한다아아아& lt;/p& gt;',
             20210616130126,
             NULL,
             NULL,
             0,
             '1');
INSERT INTO `ONPE_DEV`.`class_community`(community_number,
                                     community_class_code,
                                     community_id,
                                     community_name,
                                     community_title,
                                     community_text,
                                     community_date,
                                     community_file1,
                                     community_file2,
                                     community_count,
                                     community_auth)
     VALUES (115,
             '고려유치원_1012113',
             'jsh9870',
             '조성훈',
             '123123123',
             '& lt;p& gt;1231231231231231231231& lt;/p& gt;',
             20210616130147,
             NULL,
             NULL,
             0,
             '1');
INSERT INTO `ONPE_DEV`.`class_community`(community_number,
                                     community_class_code,
                                     community_id,
                                     community_name,
                                     community_title,
                                     community_text,
                                     community_date,
                                     community_file1,
                                     community_file2,
                                     community_count,
                                     community_auth)
     VALUES (116,
             '고려유치원_2011664',
             'jsh9870',
             '조성훈',
             '12312312312312',
             '& lt;p& gt;3123123123123123123123& lt;/p& gt;',
             20210616130156,
             NULL,
             NULL,
             0,
             '1');
INSERT INTO `ONPE_DEV`.`class_community`(community_number,
                                     community_class_code,
                                     community_id,
                                     community_name,
                                     community_title,
                                     community_text,
                                     community_date,
                                     community_file1,
                                     community_file2,
                                     community_count,
                                     community_auth)
     VALUES (117,
             '고려유치원_1012113',
             'jsh9870',
             '조성훈',
             '12312312312312',
             '& lt;p& gt;31231231231231231& lt;/p& gt;',
             20210616130207,
             NULL,
             NULL,
             0,
             '1');
INSERT INTO `ONPE_DEV`.`class_community`(community_number,
                                     community_class_code,
                                     community_id,
                                     community_name,
                                     community_title,
                                     community_text,
                                     community_date,
                                     community_file1,
                                     community_file2,
                                     community_count,
                                     community_auth)
     VALUES (118,
             '고려유치원_1012113',
             'jsh9870',
             '조성훈',
             '123123123123123',
             '& lt;p& gt;12312312312312321312& lt;/p& gt;',
             20210616130216,
             NULL,
             NULL,
             0,
             '1');
INSERT INTO `ONPE_DEV`.`class_community`(community_number,
                                     community_class_code,
                                     community_id,
                                     community_name,
                                     community_title,
                                     community_text,
                                     community_date,
                                     community_file1,
                                     community_file2,
                                     community_count,
                                     community_auth)
     VALUES (119,
             '고려유치원_1021847',
             'jsh9870',
             '조성훈',
             '1231231245214123',
             '& lt;p& gt;12312312312313& lt;/p& gt;',
             20210616130234,
             NULL,
             NULL,
             0,
             '1');
INSERT INTO `ONPE_DEV`.`class_community`(community_number,
                                     community_class_code,
                                     community_id,
                                     community_name,
                                     community_title,
                                     community_text,
                                     community_date,
                                     community_file1,
                                     community_file2,
                                     community_count,
                                     community_auth)
     VALUES (120,
             '고려유치원_1012113',
             'jsh9870',
             '조성훈',
             '123512312312313',
             '& lt;p& gt;1235123141231& lt;/p& gt;',
             20210616130243,
             NULL,
             NULL,
             0,
             '1');
INSERT INTO `ONPE_DEV`.`class_community`(community_number,
                                     community_class_code,
                                     community_id,
                                     community_name,
                                     community_title,
                                     community_text,
                                     community_date,
                                     community_file1,
                                     community_file2,
                                     community_count,
                                     community_auth)
     VALUES (121,
             '고려유치원_1021847',
             'jsh9870',
             '조성훈',
             '123123123123',
             '& lt;p& gt;12312312312312312& lt;/p& gt;',
             20210616130249,
             NULL,
             NULL,
             0,
             '1');
INSERT INTO `ONPE_DEV`.`class_community`(community_number,
                                     community_class_code,
                                     community_id,
                                     community_name,
                                     community_title,
                                     community_text,
                                     community_date,
                                     community_file1,
                                     community_file2,
                                     community_count,
                                     community_auth)
     VALUES (122,
             '고려유치원_2011664',
             'jsh9870',
             '조성훈',
             '123123124',
             '& lt;p& gt;123123123123& lt;/p& gt;',
             20210616130258,
             NULL,
             NULL,
             0,
             '1');
INSERT INTO `ONPE_DEV`.`class_community`(community_number,
                                     community_class_code,
                                     community_id,
                                     community_name,
                                     community_title,
                                     community_text,
                                     community_date,
                                     community_file1,
                                     community_file2,
                                     community_count,
                                     community_auth)
     VALUES (123,
             '고려유치원_1021847',
             'jsh9870',
             '조성훈',
             '1231231232',
             '& lt;p& gt;13131312312312& lt;/p& gt;',
             20210616130305,
             NULL,
             NULL,
             0,
             '1');
INSERT INTO `ONPE_DEV`.`class_community`(community_number,
                                     community_class_code,
                                     community_id,
                                     community_name,
                                     community_title,
                                     community_text,
                                     community_date,
                                     community_file1,
                                     community_file2,
                                     community_count,
                                     community_auth)
     VALUES (124,
             '고려유치원_1012113',
             'jsh9870',
             '조성훈',
             '214141412',
             '& lt;p& gt;31312312312312312& lt;/p& gt;',
             20210616130312,
             NULL,
             NULL,
             0,
             '1');
INSERT INTO `ONPE_DEV`.`class_community`(community_number,
                                     community_class_code,
                                     community_id,
                                     community_name,
                                     community_title,
                                     community_text,
                                     community_date,
                                     community_file1,
                                     community_file2,
                                     community_count,
                                     community_auth)
     VALUES (126,
             '고려유치원_1012113',
             'jsh9870',
             '조성훈',
             '                      ',
             '& lt;p& gt;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;& lt;/p& gt;',
             20210616140728,
             NULL,
             NULL,
             0,
             '1');
INSERT INTO `ONPE_DEV`.`class_community`(community_number,
                                     community_class_code,
                                     community_id,
                                     community_name,
                                     community_title,
                                     community_text,
                                     community_date,
                                     community_file1,
                                     community_file2,
                                     community_count,
                                     community_auth)
     VALUES (127,
             '고려유치원_1012113',
             'jsh9870',
             '조성훈',
             '아아아',
             '& lt;p& gt;1231231231231212312312123123& lt;/p& gt;',
             20210616140856,
             NULL,
             NULL,
             1,
             '1');
INSERT INTO `ONPE_DEV`.`class_community`(community_number,
                                     community_class_code,
                                     community_id,
                                     community_name,
                                     community_title,
                                     community_text,
                                     community_date,
                                     community_file1,
                                     community_file2,
                                     community_count,
                                     community_auth)
     VALUES (128,
             '고려유치원_1012113',
             'jsh9870',
             '조성훈',
             '아아ㅇㄴㅁㅇ',
             '& lt;p& gt;ㅁㄴㅇㅁㄴㅇㅁㄴㅇㅁㄴㅇㄴㅁㅌㄴㅁㅇㅁㄴㅇㅁㄴ& lt;/p& gt;',
             20210616141443,
             NULL,
             NULL,
             0,
             '1');
INSERT INTO `ONPE_DEV`.`class_community`(community_number,
                                     community_class_code,
                                     community_id,
                                     community_name,
                                     community_title,
                                     community_text,
                                     community_date,
                                     community_file1,
                                     community_file2,
                                     community_count,
                                     community_auth)
     VALUES (129,
             '고려유치원_1012113',
             'jsh9870',
             '조성훈',
             'ddddddd',
             '& lt;p& gt;ddddasdasdasd&nbsp;& lt;/p& gt;',
             20210616141506,
             NULL,
             NULL,
             0,
             '1');
INSERT INTO `ONPE_DEV`.`class_community`(community_number,
                                     community_class_code,
                                     community_id,
                                     community_name,
                                     community_title,
                                     community_text,
                                     community_date,
                                     community_file1,
                                     community_file2,
                                     community_count,
                                     community_auth)
     VALUES (130,
             '고려유치원_1012113',
             'jsh9870',
             '조성훈',
             '123123123123',
             '& lt;p& gt;123123123123&nbsp;& lt;/p& gt;',
             20210616141519,
             NULL,
             NULL,
             0,
             '1');

COMMIT;