
INSERT INTO `ONPE_DEV`.`class_community_comment`(comment_number,
                                             comment_community_number,
                                             comment_id,
                                             comment_name,
                                             comment_content,
                                             comment_date,
                                             comment_auth)
     VALUES (37,
             104,
             'hyunjoo',
             '엄현주',
             '그래 안녕',
             20210401134710,
             '1');
INSERT INTO `ONPE_DEV`.`class_community_comment`(comment_number,
                                             comment_community_number,
                                             comment_id,
                                             comment_name,
                                             comment_content,
                                             comment_date,
                                             comment_auth)
     VALUES (38,
             104,
             'hyunjoo',
             '학생',
             'ㅇㅇㅇㅇ',
             20210401135717,
             NULL);
INSERT INTO `ONPE_DEV`.`class_community_comment`(comment_number,
                                             comment_community_number,
                                             comment_id,
                                             comment_name,
                                             comment_content,
                                             comment_date,
                                             comment_auth)
     VALUES (48,
             109,
             'jsh9870',
             '조성훈',
             '학생댓글',
             20210609172503,
             NULL);
INSERT INTO `ONPE_DEV`.`class_community_comment`(comment_number,
                                             comment_community_number,
                                             comment_id,
                                             comment_name,
                                             comment_content,
                                             comment_date,
                                             comment_auth)
     VALUES (49,
             113,
             'jsh9870',
             '조성훈',
             'dddddd',
             20210616124926,
             '1');
INSERT INTO `ONPE_DEV`.`class_community_comment`(comment_number,
                                             comment_community_number,
                                             comment_id,
                                             comment_name,
                                             comment_content,
                                             comment_date,
                                             comment_auth)
     VALUES (50,
             109,
             'jsh9870',
             '조성훈',
             '123',
             20210616130036,
             '1');
INSERT INTO `ONPE_DEV`.`class_community_comment`(comment_number,
                                             comment_community_number,
                                             comment_id,
                                             comment_name,
                                             comment_content,
                                             comment_date,
                                             comment_auth)
     VALUES (51,
             109,
             'jsh9870',
             '조성훈',
             '!!!',
             20210616130038,
             '1');
INSERT INTO `ONPE_DEV`.`class_community_comment`(comment_number,
                                             comment_community_number,
                                             comment_id,
                                             comment_name,
                                             comment_content,
                                             comment_date,
                                             comment_auth)
     VALUES (52,
             109,
             'jsh9870',
             '조성훈',
             '@@@',
             20210616130040,
             '1');
INSERT INTO `ONPE_DEV`.`class_community_comment`(comment_number,
                                             comment_community_number,
                                             comment_id,
                                             comment_name,
                                             comment_content,
                                             comment_date,
                                             comment_auth)
     VALUES (53,
             109,
             'jsh9870',
             '조성훈',
             '         ',
             20210616130043,
             '1');
INSERT INTO `ONPE_DEV`.`class_community_comment`(comment_number,
                                             comment_community_number,
                                             comment_id,
                                             comment_name,
                                             comment_content,
                                             comment_date,
                                             comment_auth)
     VALUES (54,
             109,
             'jsh9870',
             '조성훈',
             '123123123123123123123124123123',
             20210616130048,
             '1');
INSERT INTO `ONPE_DEV`.`class_community_comment`(comment_number,
                                             comment_community_number,
                                             comment_id,
                                             comment_name,
                                             comment_content,
                                             comment_date,
                                             comment_auth)
     VALUES (56,
             127,
             'jsh9870',
             '조성훈',
             '아아아',
             20210616141030,
             '1');

COMMIT;