
INSERT INTO `ONPE_DEV`.`common_message`(message_number,
                                    id,
                                    name,
                                    message_content,
                                    target_id,
                                    message_date,
                                    target_authority)
     VALUES (7,
             'ikjus1',
             '송익주',
             'ㅎㅇㅎㅇㅎ',
             'test77',
             20210330151604,
             'STUDENT');
INSERT INTO `ONPE_DEV`.`common_message`(message_number,
                                    id,
                                    name,
                                    message_content,
                                    target_id,
                                    message_date,
                                    target_authority)
     VALUES (8,
             'ikjus1',
             '송익주',
             'ㅎㅇㅎㅎ',
             'test77',
             20210330151633,
             'STUDENT');
INSERT INTO `ONPE_DEV`.`common_message`(message_number,
                                    id,
                                    name,
                                    message_content,
                                    target_id,
                                    message_date,
                                    target_authority)
     VALUES (9,
             'ikjus1',
             '송익주',
             'ㅎㅇㅎㅇ',
             'test77',
             20210330152322,
             'STUDENT');
INSERT INTO `ONPE_DEV`.`common_message`(message_number,
                                    id,
                                    name,
                                    message_content,
                                    target_id,
                                    message_date,
                                    target_authority)
     VALUES (10,
             'ikjus1',
             '송익주',
             'ㅎㅇㅎㅇ',
             'test77',
             20210330152807,
             'STUDENT');
INSERT INTO `ONPE_DEV`.`common_message`(message_number,
                                    id,
                                    name,
                                    message_content,
                                    target_id,
                                    message_date,
                                    target_authority)
     VALUES (11,
             'hyunjoo',
             '엄현주',
             '현주야 안녕',
             'com1023',
             20210401134806,
             'STUDENT');
INSERT INTO `ONPE_DEV`.`common_message`(message_number,
                                    id,
                                    name,
                                    message_content,
                                    target_id,
                                    message_date,
                                    target_authority)
     VALUES (12,
             'skqkrclgh2',
             '박치호',
             'ddd',
             'skqkrclgh2',
             20210421173923,
             'STUDENT');
INSERT INTO `ONPE_DEV`.`common_message`(message_number,
                                    id,
                                    name,
                                    message_content,
                                    target_id,
                                    message_date,
                                    target_authority)
     VALUES (13,
             'skqkrclgh2',
             '박치호',
             '운동량이 부족해. 이번주에 추가 운동 배정한거 해!',
             'joo1023',
             20210506112042,
             'STUDENT');
INSERT INTO `ONPE_DEV`.`common_message`(message_number,
                                    id,
                                    name,
                                    message_content,
                                    target_id,
                                    message_date,
                                    target_authority)
     VALUES (14,
             'jsh9870',
             '조성훈',
             'test 다 ',
             'jsh9870',
             20210609140840,
             'STUDENT');
INSERT INTO `ONPE_DEV`.`common_message`(message_number,
                                    id,
                                    name,
                                    message_content,
                                    target_id,
                                    message_date,
                                    target_authority)
     VALUES (15,
             'jsh9870',
             '조성훈',
             '다시 보내는 메시지',
             'jsh9870',
             20210609173327,
             'STUDENT');
INSERT INTO `ONPE_DEV`.`common_message`(message_number,
                                    id,
                                    name,
                                    message_content,
                                    target_id,
                                    message_date,
                                    target_authority)
     VALUES (16,
             'jsh9870',
             '조성훈',
             'dddddd',
             'jsh9870',
             20210616131031,
             'STUDENT');

COMMIT;