
INSERT INTO `ONPE_DEV`.`exercise_category`(exercise_code,
                                       exercise_name,
                                       exercise_category,
                                       exercise_type,
                                       exercise_area,
                                       exercise_detail_name,
                                       exercise_count,
                                       exercise_time,
                                       exercise_url,
                                       exercise_level)
     VALUES (1,
             '홈트레이닝',
             '홈트레이닝',
             '0',
             '["건강"]',
             '팔굽혀펴기',
             '10',
             '60',
             'https://onpe.co.kr/resources/exerciseGIF/%ED%8C%94%EA%B5%BD%ED%98%80%ED%8E%B4%EA%B8%B0.gif',
             '0');
INSERT INTO `ONPE_DEV`.`exercise_category`(exercise_code,
                                       exercise_name,
                                       exercise_category,
                                       exercise_type,
                                       exercise_area,
                                       exercise_detail_name,
                                       exercise_count,
                                       exercise_time,
                                       exercise_url,
                                       exercise_level)
     VALUES (2,
             '홈트레이닝',
             '홈트레이닝',
             '0',
             '["건강"]',
             '무릎대고팔굽혀펴기',
             '10',
             '60',
             'https://onpe.co.kr/resources/exerciseGIF/%EB%AC%B4%EB%A6%8E%EB%8C%80%EA%B3%A0_%ED%8C%94%EA%B5%BD%ED%98%80%ED%8E%B4%EA%B8%B0.gif',
             '0');
INSERT INTO `ONPE_DEV`.`exercise_category`(exercise_code,
                                       exercise_name,
                                       exercise_category,
                                       exercise_type,
                                       exercise_area,
                                       exercise_detail_name,
                                       exercise_count,
                                       exercise_time,
                                       exercise_url,
                                       exercise_level)
     VALUES (3,
             '홈트레이닝',
             '홈트레이닝',
             '0',
             '["건강"]',
             '덤벨프레스',
             '10',
             '60',
             'https://onpe.co.kr/resources/exerciseGIF/%EB%8D%A4%EB%B2%A8%ED%94%84%EB%A0%88%EC%8A%A4.gif',
             '0');
INSERT INTO `ONPE_DEV`.`exercise_category`(exercise_code,
                                       exercise_name,
                                       exercise_category,
                                       exercise_type,
                                       exercise_area,
                                       exercise_detail_name,
                                       exercise_count,
                                       exercise_time,
                                       exercise_url,
                                       exercise_level)
     VALUES (5,
             '홈트레이닝',
             '홈트레이닝',
             '0',
             '["건강"]',
             '스쿼트',
             '10',
             '60',
             'https://onpe.co.kr/resources/exerciseGIF/%EC%8A%A4%EC%BF%BC%ED%8A%B8.gif',
             '0');
INSERT INTO `ONPE_DEV`.`exercise_category`(exercise_code,
                                       exercise_name,
                                       exercise_category,
                                       exercise_type,
                                       exercise_area,
                                       exercise_detail_name,
                                       exercise_count,
                                       exercise_time,
                                       exercise_url,
                                       exercise_level)
     VALUES (6,
             '홈트레이닝',
             '홈트레이닝',
             '0',
             '["건강"]',
             '런지',
             '10',
             '60',
             'https://onpe.co.kr/resources/exerciseGIF/%EB%9F%B0%EC%A7%80.gif',
             '0');
INSERT INTO `ONPE_DEV`.`exercise_category`(exercise_code,
                                       exercise_name,
                                       exercise_category,
                                       exercise_type,
                                       exercise_area,
                                       exercise_detail_name,
                                       exercise_count,
                                       exercise_time,
                                       exercise_url,
                                       exercise_level)
     VALUES (7,
             '홈트레이닝',
             '홈트레이닝',
             '0',
             '["건강"]',
             '크런치',
             '10',
             '60',
             'https://onpe.co.kr/resources/exerciseGIF/%ED%81%AC%EB%9F%B0%EC%B9%98.gif',
             '0');
INSERT INTO `ONPE_DEV`.`exercise_category`(exercise_code,
                                       exercise_name,
                                       exercise_category,
                                       exercise_type,
                                       exercise_area,
                                       exercise_detail_name,
                                       exercise_count,
                                       exercise_time,
                                       exercise_url,
                                       exercise_level)
     VALUES (8,
             '홈트레이닝',
             '홈트레이닝',
             '0',
             '["건강"]',
             '브이업',
             '10',
             '60',
             'https://onpe.co.kr/resources/exerciseGIF/v%EC%97%85.gif',
             '0');
INSERT INTO `ONPE_DEV`.`exercise_category`(exercise_code,
                                       exercise_name,
                                       exercise_category,
                                       exercise_type,
                                       exercise_area,
                                       exercise_detail_name,
                                       exercise_count,
                                       exercise_time,
                                       exercise_url,
                                       exercise_level)
     VALUES (9,
             '홈트레이닝',
             '홈트레이닝',
             '0',
             '["건강"]',
             '위아래지그재그복근',
             '10',
             '60',
             'https://onpe.co.kr/resources/exerciseGIF/%EC%9C%84%EC%95%84%EB%9E%98%EC%A7%80%EA%B7%B8%EC%9E%AC%EA%B7%B8%EB%B3%B5%EA%B7%BC.gif',
             '0');
INSERT INTO `ONPE_DEV`.`exercise_category`(exercise_code,
                                       exercise_name,
                                       exercise_category,
                                       exercise_type,
                                       exercise_area,
                                       exercise_detail_name,
                                       exercise_count,
                                       exercise_time,
                                       exercise_url,
                                       exercise_level)
     VALUES (10,
             '홈트레이닝',
             '홈트레이닝',
             '0',
             '["건강"]',
             '접었다폈다복근',
             '10',
             '60',
             'https://onpe.co.kr/resources/exerciseGIF/%EC%A0%91%EC%97%88%EB%8B%A4%ED%8F%88%EB%8B%A4%EB%B3%B5%EA%B7%BC.gif',
             '0');
INSERT INTO `ONPE_DEV`.`exercise_category`(exercise_code,
                                       exercise_name,
                                       exercise_category,
                                       exercise_type,
                                       exercise_area,
                                       exercise_detail_name,
                                       exercise_count,
                                       exercise_time,
                                       exercise_url,
                                       exercise_level)
     VALUES (11,
             '홈트레이닝',
             '홈트레이닝',
             '0',
             '["건강"]',
             '버피테스트',
             '10',
             '60',
             'https://onpe.co.kr/resources/exerciseGIF/%EB%B2%84%ED%94%BC%ED%85%8C%EC%8A%A4%ED%8A%B8.gif',
             '0');
INSERT INTO `ONPE_DEV`.`exercise_category`(exercise_code,
                                       exercise_name,
                                       exercise_category,
                                       exercise_type,
                                       exercise_area,
                                       exercise_detail_name,
                                       exercise_count,
                                       exercise_time,
                                       exercise_url,
                                       exercise_level)
     VALUES (12,
             '홈트레이닝',
             '홈트레이닝',
             '0',
             '["건강"]',
             '굿모닝',
             '10',
             '60',
             'https://onpe.co.kr/resources/exerciseGIF/%EA%B5%BF%EB%AA%A8%EB%8B%9D.gif',
             '0');

COMMIT;