
INSERT INTO `ONPE_DEV`.`notice_list`(notice_number,
                                 notice_class_code,
                                 notice_title,
                                 notice_content,
                                 notice_type,
                                 notice_date,
                                 notice_id,
                                 notice_name)
     VALUES (9,
             '서종중학교_1011510',
             '똑바로해',
             '얘들아',
             '1',
             20210326194837,
             'skqkrclgh2',
             '박치호');
INSERT INTO `ONPE_DEV`.`notice_list`(notice_number,
                                 notice_class_code,
                                 notice_title,
                                 notice_content,
                                 notice_type,
                                 notice_date,
                                 notice_id,
                                 notice_name)
     VALUES (10,
             '가나유치원_1011256',
             '공지사항 보냅니다.',
             '공지사항',
             '1',
             20210330151324,
             'ikjus1',
             '송익주');
INSERT INTO `ONPE_DEV`.`notice_list`(notice_number,
                                 notice_class_code,
                                 notice_title,
                                 notice_content,
                                 notice_type,
                                 notice_date,
                                 notice_id,
                                 notice_name)
     VALUES (11,
             '가나유치원_1011256',
             'ㅎㅇㅎ',
             'ㅎㅇㅎㅇㅎ',
             '1',
             20210330151508,
             'ikjus1',
             '송익주');
INSERT INTO `ONPE_DEV`.`notice_list`(notice_number,
                                 notice_class_code,
                                 notice_title,
                                 notice_content,
                                 notice_type,
                                 notice_date,
                                 notice_id,
                                 notice_name)
     VALUES (12,
             '가나유치원_1021925',
             'ㅎㅇㅎㅇㅎㅇㅎ',
             '공지사항',
             '1',
             20210330151756,
             'ikjus1',
             '송익주');
INSERT INTO `ONPE_DEV`.`notice_list`(notice_number,
                                 notice_class_code,
                                 notice_title,
                                 notice_content,
                                 notice_type,
                                 notice_date,
                                 notice_id,
                                 notice_name)
     VALUES (13,
             '가나유치원_1021925',
             '공지공지',
             '공지사항',
             '1',
             20210330152217,
             'ikjus1',
             '송익주');
INSERT INTO `ONPE_DEV`.`notice_list`(notice_number,
                                 notice_class_code,
                                 notice_title,
                                 notice_content,
                                 notice_type,
                                 notice_date,
                                 notice_id,
                                 notice_name)
     VALUES (14,
             '가나유치원_1021925',
             '!!',
             '공지사항',
             '1',
             20210330152846,
             'ikjus1',
             '송익주');
INSERT INTO `ONPE_DEV`.`notice_list`(notice_number,
                                 notice_class_code,
                                 notice_title,
                                 notice_content,
                                 notice_type,
                                 notice_date,
                                 notice_id,
                                 notice_name)
     VALUES (15,
             '가나유치원_1021925',
             '!!',
             '공지사항',
             '1',
             20210330152951,
             'ikjus1',
             '송익주');
INSERT INTO `ONPE_DEV`.`notice_list`(notice_number,
                                 notice_class_code,
                                 notice_title,
                                 notice_content,
                                 notice_type,
                                 notice_date,
                                 notice_id,
                                 notice_name)
     VALUES (16,
             '가나유치원_1021925',
             'ㅇㅎㅇㅎ',
             'ㅎㅇㅎㅇ',
             '1',
             20210330154210,
             'ikjus1',
             '송익주');
INSERT INTO `ONPE_DEV`.`notice_list`(notice_number,
                                 notice_class_code,
                                 notice_title,
                                 notice_content,
                                 notice_type,
                                 notice_date,
                                 notice_id,
                                 notice_name)
     VALUES (17,
             '가나유치원_1021925',
             'ㅎㅇㅎ',
             'ㅎㅇㅎㅇㅎ',
             '1',
             20210330154249,
             'ikjus1',
             '송익주');
INSERT INTO `ONPE_DEV`.`notice_list`(notice_number,
                                 notice_class_code,
                                 notice_title,
                                 notice_content,
                                 notice_type,
                                 notice_date,
                                 notice_id,
                                 notice_name)
     VALUES (18,
             '가나유치원_1021925',
             'ㅇㅇㅇㅎㅇㅇ',
             'ㅎㅇㅎㅇㅇ',
             '1',
             20210330154321,
             'ikjus1',
             '송익주');
INSERT INTO `ONPE_DEV`.`notice_list`(notice_number,
                                 notice_class_code,
                                 notice_title,
                                 notice_content,
                                 notice_type,
                                 notice_date,
                                 notice_id,
                                 notice_name)
     VALUES (19,
             '가나유치원_1021925',
             'ㅎㅇㅎ',
             'ㅎㅇㅎㅇ',
             '1',
             20210330155129,
             'ikjus1',
             '송익주');
INSERT INTO `ONPE_DEV`.`notice_list`(notice_number,
                                 notice_class_code,
                                 notice_title,
                                 notice_content,
                                 notice_type,
                                 notice_date,
                                 notice_id,
                                 notice_name)
     VALUES (20,
             '가나유치원_1021925',
             'ㅎㅇㅎㅇ',
             'ㅎㅇㅎㅇㅎ',
             '1',
             20210330155858,
             'ikjus1',
             '송익주');
INSERT INTO `ONPE_DEV`.`notice_list`(notice_number,
                                 notice_class_code,
                                 notice_title,
                                 notice_content,
                                 notice_type,
                                 notice_date,
                                 notice_id,
                                 notice_name)
     VALUES (21,
             '가나유치원_1021925',
             '!!',
             '공지사항',
             '1',
             20210330155914,
             'ikjus1',
             '송익주');
INSERT INTO `ONPE_DEV`.`notice_list`(notice_number,
                                 notice_class_code,
                                 notice_title,
                                 notice_content,
                                 notice_type,
                                 notice_date,
                                 notice_id,
                                 notice_name)
     VALUES (22,
             '가나유치원_1021925',
             'ㅎㅇㅎ',
             'ㅎㅇㅎㅇ',
             '1',
             20210330160807,
             'ikjus1',
             '송익주');
INSERT INTO `ONPE_DEV`.`notice_list`(notice_number,
                                 notice_class_code,
                                 notice_title,
                                 notice_content,
                                 notice_type,
                                 notice_date,
                                 notice_id,
                                 notice_name)
     VALUES (23,
             '가나유치원_1021925',
             '!!아자아자',
             '오늘의운동',
             '1',
             20210330160842,
             'ikjus1',
             '송익주');
INSERT INTO `ONPE_DEV`.`notice_list`(notice_number,
                                 notice_class_code,
                                 notice_title,
                                 notice_content,
                                 notice_type,
                                 notice_date,
                                 notice_id,
                                 notice_name)
     VALUES (24,
             '',
             'ㅇㅇㅇㅇ',
             'ㅇㅇ',
             '1',
             20210401114602,
             'hyunjoo',
             '엄현주');
INSERT INTO `ONPE_DEV`.`notice_list`(notice_number,
                                 notice_class_code,
                                 notice_title,
                                 notice_content,
                                 notice_type,
                                 notice_date,
                                 notice_id,
                                 notice_name)
     VALUES (25,
             '형남중학교_1011789',
             '수업공지',
             '애들아 수업공지',
             '1',
             20210401135851,
             'hyunjoo',
             '엄현주');
INSERT INTO `ONPE_DEV`.`notice_list`(notice_number,
                                 notice_class_code,
                                 notice_title,
                                 notice_content,
                                 notice_type,
                                 notice_date,
                                 notice_id,
                                 notice_name)
     VALUES (26,
             '형남중학교_1011789',
             '수업공지ㅇㅇㅇ',
             '애들아 수업공지',
             '1',
             20210401135855,
             'hyunjoo',
             '엄현주');
INSERT INTO `ONPE_DEV`.`notice_list`(notice_number,
                                 notice_class_code,
                                 notice_title,
                                 notice_content,
                                 notice_type,
                                 notice_date,
                                 notice_id,
                                 notice_name)
     VALUES (27,
             '형남중학교_1011789',
             '공징ㅇㅇㅇㅇㅇ',
             '공지보냄',
             '1',
             20210401135915,
             'hyunjoo',
             '엄현주');
INSERT INTO `ONPE_DEV`.`notice_list`(notice_number,
                                 notice_class_code,
                                 notice_title,
                                 notice_content,
                                 notice_type,
                                 notice_date,
                                 notice_id,
                                 notice_name)
     VALUES (28,
             '형남중학교_1011789',
             '공징ㅇㅇㅇㅇㅇ',
             '공지보냄',
             '1',
             20210401140009,
             'hyunjoo',
             '엄현주');
INSERT INTO `ONPE_DEV`.`notice_list`(notice_number,
                                 notice_class_code,
                                 notice_title,
                                 notice_content,
                                 notice_type,
                                 notice_date,
                                 notice_id,
                                 notice_name)
     VALUES (29,
             '서종중학교_1011510',
             '학급 공지해요 ',
             '학급 공지합니;다',
             '1',
             20210503141023,
             'skqkrclgh2',
             '박치호');
INSERT INTO `ONPE_DEV`.`notice_list`(notice_number,
                                 notice_class_code,
                                 notice_title,
                                 notice_content,
                                 notice_type,
                                 notice_date,
                                 notice_id,
                                 notice_name)
     VALUES (30,
             '서종중학교_1011510',
             '안녕하세요',
             '학급공지',
             '1',
             20210526170106,
             'skqkrclgh2',
             '박치호');
INSERT INTO `ONPE_DEV`.`notice_list`(notice_number,
                                 notice_class_code,
                                 notice_title,
                                 notice_content,
                                 notice_type,
                                 notice_date,
                                 notice_id,
                                 notice_name)
     VALUES (31,
             '고려유치원_2011664',
             '공지사항입니다.',
             '2학년 1반 공지사항',
             '1',
             20210609154753,
             'jsh9870',
             '조성훈');
INSERT INTO `ONPE_DEV`.`notice_list`(notice_number,
                                 notice_class_code,
                                 notice_title,
                                 notice_content,
                                 notice_type,
                                 notice_date,
                                 notice_id,
                                 notice_name)
     VALUES (32,
             '고려유치원_2011664',
             'ㅎㅎㅎㅎㅎㅎ',
             'ㅠㅎㅎㅎㅎ',
             '1',
             20210609180558,
             'jsh9870',
             '조성훈');
INSERT INTO `ONPE_DEV`.`notice_list`(notice_number,
                                 notice_class_code,
                                 notice_title,
                                 notice_content,
                                 notice_type,
                                 notice_date,
                                 notice_id,
                                 notice_name)
     VALUES (33,
             '',
             '테스트',
             'push 테스트',
             '1',
             20210619213901,
             'skqkrclgh2',
             '박치호');

COMMIT;