
INSERT INTO `ONPE_DEV`.`student_message`(message_number,
                                     message_class_code,
                                     message_title,
                                     message_text,
                                     message_date,
                                     message_id,
                                     message_name,
                                     message_comment_state,
                                     message_comment,
                                     message_teacher_name,
                                     message_teacher_id,
                                     message_comment_date)
     VALUES (60,
             '가나유치원_1011256',
             'ㅎㅇ',
             'ㅎㅇ',
             20210330151203,
             'test77',
             '홍성욱',
             '0',
             NULL,
             NULL,
             NULL,
             NULL);
INSERT INTO `ONPE_DEV`.`student_message`(message_number,
                                     message_class_code,
                                     message_title,
                                     message_text,
                                     message_date,
                                     message_id,
                                     message_name,
                                     message_comment_state,
                                     message_comment,
                                     message_teacher_name,
                                     message_teacher_id,
                                     message_comment_date)
     VALUES (61,
             '서종중학교_1011510',
             '안녕하슈',
             '안녕해요',
             20210330201202,
             'skqkrclgh2',
             '박치호',
             '1',
             '네 안녕하세요 근데 왜 반말이세요 장난하세[요',
             '박치호',
             'skqkrclgh2',
             20210503140831);
INSERT INTO `ONPE_DEV`.`student_message`(message_number,
                                     message_class_code,
                                     message_title,
                                     message_text,
                                     message_date,
                                     message_id,
                                     message_name,
                                     message_comment_state,
                                     message_comment,
                                     message_teacher_name,
                                     message_teacher_id,
                                     message_comment_date)
     VALUES (62,
             '형남중학교_1011789',
             '안녕ㅇㅇ',
             '안녕ㅇㅇㅇ',
             20210401115447,
             'com1023',
             '엄현주',
             '1',
             '응 안녕
',
             '엄현주',
             'hyunjoo',
             20210401134844);
INSERT INTO `ONPE_DEV`.`student_message`(message_number,
                                     message_class_code,
                                     message_title,
                                     message_text,
                                     message_date,
                                     message_id,
                                     message_name,
                                     message_comment_state,
                                     message_comment,
                                     message_teacher_name,
                                     message_teacher_id,
                                     message_comment_date)
     VALUES (63,
             '형남중학교_1011789',
             '선생님 안녕',
             '하세요',
             20210401135518,
             'hyunjoo',
             '학생',
             '1',
             '응 안녕',
             '엄현주',
             'hyunjoo',
             20210401141653);
INSERT INTO `ONPE_DEV`.`student_message`(message_number,
                                     message_class_code,
                                     message_title,
                                     message_text,
                                     message_date,
                                     message_id,
                                     message_name,
                                     message_comment_state,
                                     message_comment,
                                     message_teacher_name,
                                     message_teacher_id,
                                     message_comment_date)
     VALUES (64,
             '갈뫼중학교_1021066',
             '입장이 안됩니다',
             '입장이 안되는데 어떡하죠',
             20210401150836,
             'gmail.com123',
             '한성재',
             '0',
             NULL,
             NULL,
             NULL,
             NULL);
INSERT INTO `ONPE_DEV`.`student_message`(message_number,
                                     message_class_code,
                                     message_title,
                                     message_text,
                                     message_date,
                                     message_id,
                                     message_name,
                                     message_comment_state,
                                     message_comment,
                                     message_teacher_name,
                                     message_teacher_id,
                                     message_comment_date)
     VALUES (65,
             '갈뫼중학교_3011622',
             '안들어가져요',
             '안들어가져요',
             20210406094100,
             'didgus1213',
             '양현준',
             '0',
             NULL,
             NULL,
             NULL,
             NULL);
INSERT INTO `ONPE_DEV`.`student_message`(message_number,
                                     message_class_code,
                                     message_title,
                                     message_text,
                                     message_date,
                                     message_id,
                                     message_name,
                                     message_comment_state,
                                     message_comment,
                                     message_teacher_name,
                                     message_teacher_id,
                                     message_comment_date)
     VALUES (66,
             '서종중학교_1011510',
             '선생님 이거 스쿼트 수업할때 ',
             '허리는 어떻게 해요??',
             20210510200642,
             'skqkrclgh2',
             '박치호',
             '1',
             '허리를 잘 펴주세요. 안전사고 예방을 위해서요. ^^
',
             '박치호',
             'skqkrclgh2',
             20210510202500);
INSERT INTO `ONPE_DEV`.`student_message`(message_number,
                                     message_class_code,
                                     message_title,
                                     message_text,
                                     message_date,
                                     message_id,
                                     message_name,
                                     message_comment_state,
                                     message_comment,
                                     message_teacher_name,
                                     message_teacher_id,
                                     message_comment_date)
     VALUES (68,
             '고려유치원_1011242',
             '210',
             '210',
             20210609141027,
             'jsh9870',
             '조성훈',
             '0',
             NULL,
             NULL,
             NULL,
             NULL);
INSERT INTO `ONPE_DEV`.`student_message`(message_number,
                                     message_class_code,
                                     message_title,
                                     message_text,
                                     message_date,
                                     message_id,
                                     message_name,
                                     message_comment_state,
                                     message_comment,
                                     message_teacher_name,
                                     message_teacher_id,
                                     message_comment_date)
     VALUES (70,
             '고려유치원_2011664',
             '1',
             '1',
             20210609171140,
             'jsh9870',
             '조성훈',
             '1',
             '답변                   ',
             '조성훈',
             'jsh9870',
             20210616140648);
INSERT INTO `ONPE_DEV`.`student_message`(message_number,
                                     message_class_code,
                                     message_title,
                                     message_text,
                                     message_date,
                                     message_id,
                                     message_name,
                                     message_comment_state,
                                     message_comment,
                                     message_teacher_name,
                                     message_teacher_id,
                                     message_comment_date)
     VALUES (71,
             '서종중학교_1011510',
             '샘님',
             '잇자나뇨',
             20210610124930,
             'eltm7501',
             '김성윤',
             '0',
             NULL,
             NULL,
             NULL,
             NULL);
INSERT INTO `ONPE_DEV`.`student_message`(message_number,
                                     message_class_code,
                                     message_title,
                                     message_text,
                                     message_date,
                                     message_id,
                                     message_name,
                                     message_comment_state,
                                     message_comment,
                                     message_teacher_name,
                                     message_teacher_id,
                                     message_comment_date)
     VALUES (72,
             '고려유치원_1011534',
             '안녕ㄴㄴ',
             '안녕ㅋㅋ',
             20210616142506,
             'joo1023',
             '고려유치원',
             '1',
             '답변 합니다 엄애봉씨',
             '조성훈',
             'jsh9870',
             20210616143001);
INSERT INTO `ONPE_DEV`.`student_message`(message_number,
                                     message_class_code,
                                     message_title,
                                     message_text,
                                     message_date,
                                     message_id,
                                     message_name,
                                     message_comment_state,
                                     message_comment,
                                     message_teacher_name,
                                     message_teacher_id,
                                     message_comment_date)
     VALUES (73,
             '갈뫼중학교_1021420',
             '제목',
             '야& #40;!!& #41;♡*~_%@',
             20210619210232,
             'skqkrclgh2',
             '박치호',
             '0',
             NULL,
             NULL,
             NULL,
             NULL);

COMMIT;