platform :ios, '10.0'
use_frameworks!

project 'VisionExample.xcodeproj'

pod 'GoogleMLKit/BarcodeScanning'
pod 'GoogleMLKit/FaceDetection'
pod 'GoogleMLKit/ImageLabeling'
pod 'GoogleMLKit/ImageLabelingCustom'
pod 'GoogleMLKit/ObjectDetection'
pod 'GoogleMLKit/ObjectDetectionCustom'
pod 'GoogleMLKit/PoseDetection'
pod 'GoogleMLKit/PoseDetectionAccurate'
pod 'GoogleMLKit/TextRecognition'
pod "YoutubePlayer-in-WKWebView", "~> 0.3.0"
pod 'Alamofire', '~> 5.2'
pod 'SDWebImage', '~> 5.0'
pod 'Firebase/Analytics'
pod 'Firebase/Messaging'
pod 'Firebase/Auth'
pod 'GoogleSignIn'

target 'VisionExample' do
end

target 'VisionExampleObjc' do
end
