platform :ios, '11.0'
use_frameworks!

project 'VisionExample.xcodeproj'

pod 'GoogleMLKit/BarcodeScanning'
pod 'GoogleMLKit/FaceDetection'
pod 'GoogleMLKit/ImageLabeling'
pod 'GoogleMLKit/ImageLabelingCustom'
pod 'GoogleMLKit/ObjectDetection'
pod 'GoogleMLKit/ObjectDetectionCustom'
pod 'GoogleMLKit/PoseDetection'
pod 'GoogleMLKit/PoseDetectionAccurate'
pod 'GoogleMLKit/TextRecognition'
pod "YoutubePlayer-in-WKWebView", "~> 0.3.0"
pod 'Alamofire', '~> 5.2'
pod 'SDWebImage', '~> 5.0'
pod 'Firebase/Analytics'
pod 'Firebase/Messaging'
pod 'Firebase/Auth'
pod 'GoogleSignIn'

pod 'KakaoSDKCommon'  # 필수 요소를 담은 공통 모듈
pod 'KakaoSDKAuth'    # 사용자 인증
pod 'KakaoSDKUser'    # 카카오 로그인, 사용자 관리
pod 'KakaoSDKTalk'    # 친구, 메시지(카카오톡)

pod 'naveridlogin-sdk-ios'

target 'VisionExample' do
end

target 'VisionExampleObjc' do
end
